---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pgadmin
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/pgadmin/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: security-external-secrets-stores
#    - name: system-volsync
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
