---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudflare-exporter
  namespace: flux-system
spec:
  interval: 1h
  url: https://lablabs.github.io/cloudflare-exporter/
