---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.5.4
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9798
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            path: /metrics
            interval: 60m
            scrapeTimeout: 1m
    nodeSelector:
      node-role.kubernetes.io/worker: worker
