---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
#    - name: volsync
#      namespace: volsync
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.13.4@sha256:529f1be5e677b13fcef5e344afc7643df0c7bec6a3185a2777ece757dff70e2b
    env:
      TZ: Australia/Melbourne
    service:
      main:
        ports:
          http:
            port: 8181
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "{{ .Release.Name }}.davidstewen.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      add-ons:
        enabled: true
        type: emptyDir
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 500Mi
    sidecars:
      jbops:
        image: registry.k8s.io/git-sync/git-sync:v4.1.0
        imagePullPolicy: IfNotPresent
        args:
          - --repo=https://github.com/blacktwin/JBOPS
          - --branch=master
          - --wait=86400 # 1 day
          - --root=/add-ons
        volumeMounts:
          - { name: add-ons, mountPath: /add-ons }
