apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:j6423D+MNbHt,iv:QtyzKhmTuALm3fqRMHX7hZa+QUUqFVHOa2YbJ1mW+R8=,tag:uEfcxTkVNz8P3ufF3Cuj2w==,type:str]
    admin-user: ENC[AES256_GCM,data:oqWrD2I=,iv:WFMaFUKUSvoMXWbhmxQEbqziDyR2PfhAbfxKPdoY3y0=,tag:x79lsqIWX1MK7mF2skIvlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMVpiT3YzdWNubVR1T1BV
            aSt0NmRIVVhJczBwTk5LcUVKYlRKU2xLK2lBCkFpc1c4bGpJWDIrZmZMRXV3eVpl
            ZHA1cDdvbzBPNXI3NXlLYUpDUnNabU0KLS0tIEErajkyRzN1Rmc3U2xCNUFGZXR4
            ZWZ1V2VMdEhId21YVlhxMTFjNi8rNGMKXjxkKElj7AyAyyhL6pwO1MTHG+Edfp5d
            RgAcgucXFKXJIJWkDpXlhlA++AjFL/h3iiWvjIkE7xUkNsqsO1TnpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-14T02:47:09Z"
    mac: ENC[AES256_GCM,data:sZl6h+SwvOD1xI8jzjT13vQiWpahd1efI70mohcHWWoxhRNUslnEzC+SP/iz9rzfWj2carsyCSrji7be2TbWSRG/tWPAyZC6l2yHwOLRzawYlhtGFpuGqAnVgz8gYwB77InaEDaf4w9bUbTQ0hKWJw+244BvGeLVYChCjHOz18M=,iv:TXOQUr40B73MZ2pCPKvShlejiLiyZf5gSrcofpk488Q=,tag:LeRJr4w8fH60ddWuUHIVAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
