---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app paperless
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 65539
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16.1"
            envFrom:
              - secretRef:
                  name: paperless-dbinit-secret

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.6.3
            env:
              COMPOSE_PROJECT_NAME: paperless
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_PORT: 8000
              PAPERLESS_REDIS: redis://paperless-redis.databases.svc.cluster.local.:6379
              PAPERLESS_TASK_WORKERS: 2
              PAPERLESS_TIKA_ENABLED: true
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
              PAPERLESS_TIKA_ENDPOINT: http://tika:9998
              PAPERLESS_TIME_ZONE: Australia/Victoria
              PAPERLESS_URL: https://{{ .Release.Name }}.davidstewen.com
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
              PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME
              PAPERLESS_LOGOUT_REDIRECT_URL: https://id.davidstewen.com/logout
            envFrom:
              - secretRef:
                  name: paperless-secret

          gotenburg:
            name: gotenburg
            image:
              repository: ghcr.io/mchestr/gotenberg
              tag: 8.2.1
            env:
              - name: DISABLE_GOOGLE_CHROME
                value: "1"

          tika:
            name: tika
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-full

          redis:
            name: redis
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.4@sha256:e647cfe134bf5e8e74e620f66346f93418acfc240b71dd85640325cb7cd01402

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8000

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-method: GET
          nginx.ingress.kubernetes.io/auth-url: http://authentik.security.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://id.davidstewen.com?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: paperless.png
          gethomepage.dev/name: Paperless
          gethomepage.dev/group: Home
          gethomepage.dev/widget.type: paperlessngx
          gethomepage.dev/widget.url: http://paperless.default.svc.cluster.local:8000
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PAPERLESS_API_TOKEN}}"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:barcode-scan
          hajimari.io/appName: "Paperless"
          hajimari.io/group: "Home"
        hosts:
          - host: &host "{{ .Release.Name }}.davidstewen.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /data/local
      data:
        enabled: true
        existingClaim: data-paperless
        globalMounts:
          - subPath: data
            path: /usr/src/paperless/data
          - subPath: media
            path: /usr/src/paperless/media
