apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dYo42+NeO1B36tU5Bhhsyxn6pXh7XhbT,iv:fWAETUzfZkxeObbVhDIq9mqhojouAfb43Y0FRgVJ5Uc=,tag:S4JHqwrEwZSL5lTNcJGI5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWFQyNTBoRjQrRGEyazhJ
            a2t3TThTNm05Z2R2Z0RMZWY5ZmxKeEJFRFE0Cno0V3B3MnEzS3dndFZ1MU5ZQXlu
            QVIwZTk2cW43L1c5N2E4UitRVjJSbDgKLS0tIFdLNytYQWwzajUwSHFDd1dVbzd6
            NzhoaWZUWEJDRUN1ZzRWeHZJTTlsVGMKbX45lM8gtFT4K/TLvoebcvWUmS1HJahl
            nUpnYCx886lmU4AhBZnqpeWRVIw7wzUkl3eu1QdKc3vuBV4cH5y2EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-14T02:47:06Z"
    mac: ENC[AES256_GCM,data:fRgvW55wlrIgNL3eXoSkPvS35wEJUT1BaOH1jxAUBhmIAuOeGalZUPmwUUU/EQ8T6thGbu4ITjjQE8Oem2W/p94oETA7UHwRd+2sbX1DUFj/j2jRlPFQEwri4D7OK4BmJbAiVHrOLlUkAUS20jmw4q1Wf6UEouxPsXerZLwKvwU=,iv:hlguUNVF0pYW7kfz7aisQB6w8I9eqc2jzzGbHMFUO/U=,tag:p2ZUDfruYHi6D6ZhsbjphQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
