---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: kube-system
#    - name: intel-device-plugin-gpu
#      namespace: kube-system
#    - name: rook-ceph-cluster
#      namespace: rook-ceph
#    - name: volsync
#      namespace: volsync
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.11@sha256:47762d22596e76f7d778b179a83f4c119151d009ae0bfd2286e260d5b2fc50a8
    env:
#      DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
#      JELLYFIN_FFmpeg__probesize: 50000000
#      JELLYFIN_FFmpeg__analyzeduration: 50000000
      JELLYFIN_PublishedServerUrl: &loadBalancerIP 192.168.10.223
      TZ: Australia/Victoria
#      JELLYFIN_CACHE_DIR: "/config/cache"
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: *loadBalancerIP
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: &port 8096
    # serviceMonitor:
    #   main:
    #     enabled: true
#    probes:
#      liveness: &probes
#        enabled: true
#        custom: true
#        spec:
#          httpGet:
#            path: /health
#            port: *port
#          initialDelaySeconds: 0
#          periodSeconds: 10
#          timeoutSeconds: 1
#          failureThreshold: 3
#      readiness: *probes
#      startup:
#        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          hajimari.io/enable: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
#    podSecurityContext:
#      runAsUser: 568
#      runAsGroup: 568
#      fsGroup: 568
#      fsGroupChangePolicy: OnRootMismatch
#      supplementalGroups: [44, 105, 10000]
#    volumeClaimTemplates:
#      - name: jellyfin-config
#        mountPath: /config
#        accessMode: ReadWriteOnce
#        size: 50Gi
#        storageClass: synology-iscsi-retain
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        mountPath: /config
      media:
        enabled: true
        type: nfs
        server: "192.168.10.15"
        path: /volume2/piNFS01/jellyfin
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
#    nodeSelector:
#      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      requests:
#        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
#        gpu.intel.com/i915: 1
        memory: 4000Mi
