---
# yaml-language-server: $schema=http://kubernetes-schemas.local.lan:8080/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/osnabrugge/pihole-exporter
      tag: v0.4.0@sha256:5a7f81273e45fab327e5083a6f3d33cb872e2183e5fc64eac9ce5bc4ce675f51
    env:
      PIHOLE_HOSTNAME: 192.168.10.195
      PORT: 9617
    envFrom:
      - secretRef:
          name: pihole-exporter-secret
    resources:
      requests:
        cpu: 15m
        memory: 30M
      limits:
        memory: 60M

    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9617
    nodeSelector:
      node-role.kubernetes.io/worker: worker
