---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    controller:
      type: statefulset
      annotations:
        configmap.reloader.stakater.com/reload: qbittorrent-scripts
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.6.1@sha256:796f135bcb572a3fb3138b0c65034535c0a7b1dcb83940fe12e00cad1b47fcbb
    env:
      TZ: Australia/Melbourne
      QBITTORRENT__PORT: &port 80
      QBITTORRENT__BT_PORT: &bittorrentPort 50413
    service:
      main:
        ports:
          http:
            port: *port
          cross-seed:
            port: 2468
      bittorrent:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.10.223
        ports:
          bittorrent:
            enabled: true
            port: *bittorrentPort
            protocol: TCP
            targetPort: *bittorrentPort
        externalTrafficPolicy: Cluster
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: true
          hajimari.io/icon: mdi:download
        hosts:
          - host: &host qb.davidstewen.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
    # Note: If downloading very large torrents it might be worth using NFS for your download directory.
    # Beware if you are downloading torrents directly to a ZFS dataset that dataset will accrue fragmentation.
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/plex/media
        mountPath: /media
      incomplete:
        enabled: true
        type: emptyDir
      completed-script:
        enabled: true
        type: configMap
        name: qbittorrent-scripts
        mountPath: /scripts/completed.sh
        subPath: completed.sh
        defaultMode: 0775
        readOnly: true
    nodeSelector:
      node-role.kubernetes.io/worker: worker
#    affinity:
#      podAntiAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#                - key: app.kubernetes.io/name
#                  operator: In
#                  values: ["sabnzbd"]
#            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 16Gi
