---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snmp-generator
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      image: quay.io/prometheus/snmp-generator:v0.24.1
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - cp -f /opt/snmp.yml /etc/snmp_exporter
      volumeMounts:
      - name: config
        mountPath: /etc/snmp_exporter

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: quay.io/prometheus/snmp-exporter
      # TODO: Switch to release tag on next release
      tag: v0.25.0@sha256:cf0768ea183aba8a91bc30e76edeed26790d32b23d37d1473337931ecd05cb8c
    env:
      TZ: Australia/Victoria
#    resources:
#      requests:
#        cpu: 15m
#        memory: 30M
#      limits:
#        memory: 60M
    volumeMounts:
      - name: config
        mountPath: /etc/snmp_exporter
#    service:
#      main:
#        ports:
#          http:
#            enabled: false
#          metrics:
#            enabled: true
#            protocol: TCP
#            port: 9617
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - worker
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
