---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app snmp-generator
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    controllers:
      snmp-generator:
        initContainers:
          init-generator:
            image:
              repository: quay.io/prometheus/snmp-generator
              tag: v0.25.0@sha256:df6554584509a3ae49f0258ae8b4fb15cf9bff39672b7e2d51ee5c461e5262fb
        containers:
          app:
            image:
              repository: quay.io/prometheus/snmp-exporter
              tag: v0.25.0@sha256:cf0768ea183aba8a91bc30e76edeed26790d32b23d37d1473337931ecd05cb8c
            env:
              TZ: Australia/Victoria
            command: "/bin/sh"
            resources:
              requests:
                cpu: 15m
                memory: 30M
              limits:
                memory: 60M
    service:
      app:
        controller: *app
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9617
    serviceMonitor:
      app:
        enabled: true
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 5m
          scrapeTimeout: 1m

