---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: system
  values:

    controllers:
      main:
        type: statefulset

        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/calibre
              tag: 7.9.0

            env:
              TZ: ${TZ}
              PUID: 568
              PGID: 568
              FM_HOME: /media/calibre

            resources:
              requests:
                cpu: 15m
                memory: 249M

            probes:
              startup:
                spec:
                  initialDelaySeconds: 60
                  failureThreshold: 160
    service:
      main:
        ports:
          http:
            port: 8080

      # webserver:
      #   enabled: true
      #   ports:
      #     webserver:
      #       enabled: true
      #       port: 8081
      #       protocol: TCP
      #       targetPort: 8081
      #   type: LoadBalancer
      #   externalTrafficPolicy: Cluster
      #   loadBalancerIP: ${LB_CALIBRE}

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          # authentik.home.arpa/enabled: "true"
        hosts:
          - host: &host "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - secretName: *host
            hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: *app
      media:
        enabled: true
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/plex/media
        globalMounts:
          - path: /media
