---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.8.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: *secret
      addPrometheusAnnotations: false
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64

    authentik:
      log_level: info
      avatars: "gravatar,initials"
      email:
        host: smtp-relay.home.svc.cluster.local
        port: 2525
        from: "Access <dstewen@internode.on.net>"
      error_reporting:
        enable: false
        send_pii: false
      redis:
        host: dragonfly.database.svc.cluster.local
        db: 4
    prometheus:
      rules:
        enabled: true
    server:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 2
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.3@sha256:8ba3204f6b293dd168766009aae2ce4fa986a29b931c2d30ac1b30238ac750b8
          envFrom:
            - secretRef:
                name: *secret
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 200M
        limits:
          memory: 700M
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:webauthn
          hajimari.io/group: Security
          hajimari.io/appName: Authentik
          hajimari.io/url: https://id.${SECRET_DOMAIN}
#          gethomepage.dev/enabled: "true"
#          gethomepage.dev/icon: authentik.png
#          gethomepage.dev/name: Authentik
#          gethomepage.dev/group: Infrastructure
#          gethomepage.dev/description: OIDC User Management
#          gethomepage.dev/widget.type: authentik
#          gethomepage.dev/widget.url: http://authentik-server.security.svc.cluster.local
#          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - id.${SECRET_DOMAIN}
        https: false
    worker:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 2
      resources:
        requests:
          cpu: 15m
          memory: 200M
        limits:
          memory: 700M
      metrics:
        serviceMonitor:
          enabled: true
