---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app s3700-24t4f-snmp-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: s3700-24t4f-snmp-exporter
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: s3700-24t4f-snmp-exporter
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: s3700-24t4f-snmp-exporter
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: s3700-24t4f
          target: 192.168.10.3
          module:
            - if_mib
      scrapeTimeout: 30s
#      scrapeInterval: 60s
      relabelings:
#        - source_labels: [__address__]
#          target_label: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
#        - target_label: __address__
#          replacement: s3700-24t4f-snmp-exporter:9116
