---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-immich
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-redis
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/media/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
