---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ceph-filesystem
