---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-calibre
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-volsync
  path: ./kubernetes/apps/media/calibre/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
