---
# yaml-language-server: $schema=https://kubernetes-schemas.kashall.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smartctl-exporter-arm64
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    image:
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.7.0"
    config:
      devices:
        - /dev/nvme0n1
    nodeSelector:
      kubernetes.io/arch: arm64
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
