---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter-arm64
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    image:
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.7.0"
    config:
      bind_to: "0.0.0.0:9633"
      url_path: "/metrics"
      smartctl_location: /usr/sbin/smartctl
      collect_not_more_than_period: 120s
      devices:
        - /dev/nvme0n1
    nodeSelector:
      kubernetes.io/arch: arm64
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
