---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    image:
      repository: ghcr.io/joryirving/smartctl_exporter
      tag: 0.12.0@sha256:f389e682101fe727c288cee12df19a4e49f8ce3f158e9ef7d056db9d541a361f
    config:
      devices:
        - /dev/sda
        - /dev/nvme0n1
    nodeSelector:
      kubernetes.io/arch: amd64
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
