---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minecraft-ftb
  namespace: gameserver
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft
      version: 4.11.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    livenessProbe:
      command:
        - mc-monitor
        - status
        - --host
        - localhost
      initialDelaySeconds: 60
      periodSeconds: 10
    readinessProbe:
      command:
        - mc-monitor
        - status
        - --host
        - localhost
      initialDelaySeconds: 60
      periodSeconds: 10
    image:
      repository: itzg/minecraft-server
      tag: java8-multiarch@sha256:094a9e4c2f1edabd2dff1e97d9f39c4a8e872ca62961279e1a5ed4d6aa8a4c8f
    minecraftServer:
      eula: "TRUE"
      version: "1.12.2"
      type: "FTBA"
      ftbModpackId: "35"
      ftbModpackVersionId: "3.6.0"
      difficulty: hard
      pvp: true
      memory: 6144M
      serviceType: LoadBalancer
      motd: "FTB:R"
      loadBalancerIP: "${LB_MINECRAFT_IP}"
      externalTrafficPolicy: Local
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-ftb-data-v1
    resources:
      requests:
        cpu: 34m
        memory: 4506M
      limits:
        memory: 5279M
