---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-home-ops-amd64
  namespace: actions-runner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-runner-set-home-ops-amd64-runner
    githubConfigUrl: https://github.com/dstewen/flux-cluster
    githubConfigSecret: pre-defined-secret
    minRunners: 1
    maxRunners: 2
    containerMode:
      type: dind
    template:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                  - worker
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: actions.github.com/scale-set-name
                        operator: In
                        values:
                          - arc-runner-set-home-ops-amd64-runner
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: runner
            image: ghcr.io/joryirving/actions-runner:2.317.0@sha256:490d5a28d9e1ae848f5106f725eff4b3b804792edd0823d1b583edb0f79e9feb
            command: ["/home/runner/run.sh"]
#    listenerTemplate:
#      metadata:
#        annotations:
#          prometheus.io/scrape: "true"
#          prometheus.io/path: "/metrics"
#          prometheus.io/port: "8080"
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
#  valuesFrom:
#    - kind: Secret
#      name: actions-runner-controller-auth-secret
#      valuesKey: github_app_id
#      targetPath: githubConfigSecret.github_app_id
#    - kind: Secret
#      name: actions-runner-controller-auth-secret
#      valuesKey: github_app_installation_id
#      targetPath: githubConfigSecret.github_app_installation_id
#    - kind: Secret
#      name: actions-runner-controller-auth-secret
#      valuesKey: github_app_private_key
#      targetPath: githubConfigSecret.github_app_private_key
    nodeSelector:
      node-role.kubernetes.io/worker: worker
