---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-synology-nas
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-snmp-exporter
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: *app
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: synology-nas-0
          target: 192.168.10.15
          module:
            - synology
      path: /snmp
#      scrapeTimeout: 30s
#      scrapeInterval: 60s
      relabelings:
#        - source_labels: [__address__]
#          target_label: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
#        - target_label: __address__
#          replacement: synology-nas-snmp-exporter:9116
    nodeSelector:
      node-role.kubernetes.io/worker: worker
