---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app netboot
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      netboot:
        containers:
          app:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: 0.7.1-nbxyz1
    defaultPodOptions:
      hostNetwork: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
      web:
        enabled: true
        primary: false
        type: LoadBalancer
        loadBalancerIP: 192.168.10.229
        controller: app
        externalTrafficPolicy: Cluster
        ports:
          web:
            enabled: true
            primary: false
            port: 80
            targetPort: 80
            protocol: HTTP
      tftp:
        enabled: true
        primary: false
        controller: app
        type: NodePort
        ports:
          tftp:
            enabled: true
            primary: false
            port: 69
            targetPort: 69
            protocol: UDP
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host netboot.davidstewen.com
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  identifier: app
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 2Gi
        globalMounts:
          - path: /config
        retain: true
      data:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 50Gi
        globalMounts:
          - path: /assets
        retain: true
