---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netboot
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: 0.7.1-nbxyz3

    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
      hostNetwork: true

    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
      web:
        enabled: true
        primary: false
        type: LoadBalancer
        loadBalancerIP: 192.168.10.229
        controller: main
        externalTrafficPolicy: Cluster
        ports:
          web:
            enabled: true
            primary: false
            port: 80
            targetPort: 80
            protocol: HTTP
      tftp:
        enabled: true
        primary: false
        controller: main
        type: NodePort
        ports:
          tftp:
            enabled: true
            primary: false
            port: 69
            targetPort: 69
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Netboot.xyz"
          hajimari.io/info: "Network boot system"
          hajimari.io/icon: "refresh-auto"
        hosts:
          - host: &host netboot.davidstewen.com
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 2Gi
        globalMounts:
          - path: /config
        retain: true
      data:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 50Gi
        globalMounts:
          - path: /assets
        retain: true
