---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
#  - config-map.yaml
  - helm-release.yaml
configMapGenerator:
  - name: snmp-exporter-synology
    files:
      - snmp.yaml=./snmp.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
#  labels:
#    grafana_dashboard: "true"
