---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app node-red
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/nodered/node-red
              tag: 3.1.6@sha256:9f1ed3d12b10fa93d5f13e575543d169c98e34556423ed1d1aff0ecb3b885697
            env:
              TZ: ${TIMEZONE}
#              NODE_RED_ENABLE_PROJECTS: "true"
#              NODE_RED_ENABLE_SAFE_MODE: "false"
              NODE_RED_OAUTH_ISSUER_URL: "https://id.${SECRET_DOMAIN}/application/o/node-red/"
              NODE_RED_OAUTH_AUTH_URL: "https://id.${SECRET_DOMAIN}/application/o/authorize/"
              NODE_RED_OAUTH_CALLBACK_URL: "https://nr.${SECRET_DOMAIN}/auth/strategy/callback/"
              NODE_RED_OAUTH_TOKEN_URL: "https://id.${SECRET_DOMAIN}/application/o/token/"
              NODE_RED_OAUTH_USER_URL: "https://id.${SECRET_DOMAIN}/application/o/userinfo/"
            envFrom:
              - secretRef:
                  name: node-red-secret
            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 512M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: cib:node-red
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths: &paths
              - path: /
                service:
                  name: main
                  port: http
          - host: &customHost "nr.${SECRET_DOMAIN}"
            paths: *paths
        tls:
          - hosts:
              - *host
              - *customHost
    persistence:
      data:
        enabled: true
        existingClaim: *app
      config-file:
        type: configMap
        name: node-red-configmap
        globalMounts:
          - path: /data/settings.js
            subPath: settings.js
            readOnly: true
      tmp:
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 1880
