apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:uZKODFIhbf03KuiZ,iv:oYIRqlfiSCrMX1Z2l0m0JwKBFQCSfGaT9xNeRxw4TD0=,tag:F/YJta1TpDZ7gNUqGzBwVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVVNjUVAzSU5PSTFiRUl0
            VWhtZ2dIazYyQlRCTTNQZ3o2dHpram5YYzNNClRZUDk0NWl1c09VV20rTGlWdytC
            WWx5Rk5WRHdxNk93Y2Y3dGdKS1M4UkUKLS0tIHREOVdLcGgraXcvWE5INkxQM0Z6
            eUtVVEdCZHNUQXNUQUVVcHNrb1VKZ3MKSUFzk31Uv8Esl8joL+Ts92mMItVH/a3A
            kbIFQ4ymQhEZzL0xsfus4EJvK9uyH3Gi+EMnFlC9J8l0LXCi9yz1gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-14T02:47:06Z"
    mac: ENC[AES256_GCM,data:IvZ8F0ExQ6ZyRWTMwu4clQsQyLhN+9AlLjEy89WnCo7CxWnx3StZsIW6kWEHPp6HaTiX67UcKukrwl/k8iYeawpfGwISZsTskf80NdvVXAJRDUrGVIE8NtIj+5YnR+aVaqPSLtr8Z5B16FilV0KBWech7oau2F36GhO03ibI/HE=,iv:ZznvpS2ju8hSCjOuh7oRB/oIVwhu8y/Fu9beH0xSO3I=,tag:SafH/fc6oaCE5qximPMfag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
