apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Se7vH2rnP0m/UkK1nZdk2791I+6Z,iv:YFVkLHJ3NZQ5a0rArfHsl9t7nNP1mpcSYSlz/vdz3Wg=,tag:F3SpdKvQ/QHexcuwpwaSyg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:INaJRgcDgyfZ5hm9Yz1OlPlTDlofGZZL+lBwUGZi0+T9C6x7,iv:fOILIra41CKzlrzHnZyfOu+ThTE0Zt2Z44RuHfKb0qQ=,tag:4wvYrQDhRyNofJ0qGy+B4g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:QyB8yHZNe/7WP6Krfnpw,iv:+ORt0+I9T/DXnmwKGTGNuB+e+GSIrxGFKrGCzrB2VxQ=,tag:noELbuIWQcF8V/pYn5C+HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYzlPNDlheDZhbXNuUGRR
            L2NsMGcvYS9QMTc2eHFZa3R2cFZlOGYwTEFrClY1ZytsN3NHbHR6ZzdtTC9Qa0FJ
            MjZ2NFhUTDh3QXRkc0p6ZmRYeFlXMEEKLS0tIHl0NGhEVSsxY0VCNVVEakJKa0ZD
            a1hUYmFYYUVVZWNta0FycDlnY0lvRlEK6iTnm6+RQUYjXS964Q0CCDswaYAUe76K
            9rJmdbGXs5eD8wy6gqUq4RcUjSRZLsUqoBVzb/WbYTur7le9jcnaIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-17T02:19:33Z"
    mac: ENC[AES256_GCM,data:MwsrFwH2/X1LMzvUZ7Id7+hA9vI+pUhdM9Zqve6vOCE4QLk7p93KDejVNAUz3EiVEK97ca/GcC90CDFIjaoY700yAoYrRB9YHXm/gVFxlsrBySHS0yhcH+PKGFaFcbwvS6IyQX6nN9heVSIql734ID5jKCpFTQr0hNglQg1MIuE=,iv:CLDRAuqj6W+8zL2XVk8iY5Dajr70cuRvbIzhGtg1zUk=,tag:mhca3+1YRRrpsD6V2G03ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
