---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-microservices
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-server
      namespace: media
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 65539
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.91.3
            command: /bin/sh
            args:
              - ./start-microservices.sh
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 1Gi

    service:
      main:
        ports:
          http:
            port: 3002

    persistence:
      data:
        enabled: true
        type: nfs
        server: 192.168.10.15
        path: /volume1/shared/media/photos
        globalMounts:
          - path: /usr/src/app/upload
