---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - pgadmin-secret.yaml
  - helmrelease.yaml
#  - volsync-config.yaml
configMapGenerator:
  - name: servers-json
    files:
      - config/servers.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
