---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr-node
  namespace: media

spec:

  interval: 15m

  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        supplementalGroups:
          - 34
          - 44
          - 100
          - 109
          - 226
          - 1568
          - 65534
        # capabilities:
        #   add:
        #     - CHOWN

    controllers:
      tdarr-node:
        type: daemonset

        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node_acc
              tag: 2.00.20.1

            env:
              TZ: ${TIMEZONE}
              PUID: "1000"
              PGID: "1000"
              serverIP: tdarr-main.media.svc.cluster.local
              serverPort: 8266
              ffmpegPath: "/usr/local/bin/ffmpeg"
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName

            # nodeSelector:
            #   feature.node.kubernetes.io/pci-0300_1002.present: "true"

            ports:
              - name: http
                containerPort: &port 8265

            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 2000m
                memory: 2048Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4096Mi

    # service:
    #   main:
    #     enabled: false
    #     controller: main
    #     ports:
    #       enabled: false
    #       http:
    #         port: *port

    persistence:

#      media:
#        # enabled: true
#        existingClaim: nfs-media

      movies:
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/plex/media/Movies
        globalMounts:
          - path: /mnt/movies

      tv:
        type: nfs
        server: 192.168.10.15
        path: "/volume2/piNFS01/flux-cluster/plex/media/TV Shows"
        globalMounts:
          - path: /mnt/tv

      other_videos:
        type: nfs
        server: 192.168.10.15
        path: "/volume2/piNFS01/flux-cluster/plex/media/Other Videos"
        globalMounts:
          - path: /mnt/other_videos
