global:
#  slack_api_url: "${ALERT_MANAGER_DISCORD_WEBHOOK}"
  resolve_timeout: 5m
receivers:
  - name: 'null'
#  - name: 'discord'
#    slack_configs:
#      - api_url: "${ALERT_MANAGER_DISCORD_WEBHOOK}"
#        channel: '#prometheus'
#        send_resolved: true
#        title: |-
#          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }} {{ else if ne .CommonAnnotations.message ""}}{{ .CommonAnnotations.message }} {{ else if ne .CommonAnnotations.description ""}}{{ .CommonAnnotations.description }} {{ else }}{{ .CommonLabels.alertname }}{{ end }}
#        text: >-
#          {{ range .Alerts -}}
#            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end
#          {{ if ne .Annotations.summary ""}}*Summary:* {{ .Annotations.summary }} {{ else if ne .Annotations.message ""}}*Message:* {{ .Annotations.message }} {{ else if ne .Annotations.description ""}}*Description:* {{ .Annotations.description }}{{ end
#          *Details:*
#            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#            {{ end }}
#          {{ end }}
#  - name: 'discord-ceph'
#    slack_configs:
#      - api_url: "${ALERT_MANAGER_DISCORD_WEBHOOK_CEPH}"
#        channel: '#storage'
#        send_resolved: true
#        title: |-
#          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }} {{ else if ne .CommonAnnotations.message ""}}{{ .CommonAnnotations.message }} {{ else if ne .CommonAnnotations.description ""}}{{ .CommonAnnotations.description }} {{ else }}{{ .CommonLabels.alertname }}{{ end }}
#        text: >-
#          {{ range .Alerts -}}
#            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end
#          {{ if ne .Annotations.summary ""}}*Summary:* {{ .Annotations.summary }} {{ else if ne .Annotations.message ""}}*Message:* {{ .Annotations.message }} {{ else if ne .Annotations.description ""}}*Description:* {{ .Annotations.description }}{{ end
#          *Details:*
#            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#            {{ end }}
#          {{ end }}
  - name: pushover
    pushover_configs:
      - html: true
        message: |-
          {{ "{{-" }} range .Alerts {{ "}}" }}
            {{ "{{-" }} if ne .Annotations.description "" {{ "}}" }}
              {{ "{{" }} .Annotations.description {{ "}}" }}
            {{ "{{-" }} else if ne .Annotations.summary "" {{ "}}" }}
              {{ "{{" }} .Annotations.summary {{ "}}" }}
            {{ "{{-" }} else if ne .Annotations.message "" {{ "}}" }}
              {{ "{{" }} .Annotations.message {{ "}}" }}
            {{ "{{-" }} else {{ "}}" }}
              Alert description not available
            {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} if gt (len .Labels.SortedPairs) 0 {{ "}}" }}
              <small>
              {{ "{{-" }} range .Labels.SortedPairs {{ "}}" }}
                <b>{{ "{{" }} .Name {{ "}}" }}:</b> {{ "{{" }} .Value {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
              </small>
            {{ "{{-" }} end {{ "}}" }}
          {{ "{{-" }} end {{ "}}" }}
        priority: |-
          {{ "{{" }} if eq .Status "firing" {{ "}}" }}1{{ "{{" }} else {{ "}}" }}0{{ "{{" }} end {{ "}}" }}
        send_resolved: true
        sound: gamelan
        title: >-
          {{ "{{" }} .CommonLabels.alertname {{ "}}" }}
          [{{ "{{" }} .Status | toUpper {{ "}}" }}{{ "{{" }} if eq .Status "firing" {{ "}}" }}:{{ "{{" }} .Alerts.Firing | len {{ "}}" }}{{ "{{" }} end {{ "}}" }}]
        token: "{{ .PUSHOVER_TOKEN }}"
        url_title: View in Alertmanager
        user_key: "{{ .PUSHOVER_USER_KEY }}"
route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  receiver: "discord"
  routes:
    - receiver: "null"
      match:
        alertname: KubeCPUOvercommit
    - receiver: "null"
      match:
        alertname: PrometheusRuleFailures
    - receiver: "null"
      match:
        alertname: Watchdog
#    - receiver: "discord"
#      match_re:
#        severity: critical
#      continue: true
#    - receiver: "discord-ceph"
#      match_re:
#        ceph: ceph
#      continue: true
    - receiver: pushover
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
