---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-exporter
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        CF_API: "{{ .CF_API_GRAFANA_REPORTING }}"
  dataFrom:
    - extract:
        key: cloudflare
