---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudflare-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    controllers:
      cloudflare-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lablabs/cloudflare_exporter
              tag: 0.0.16
            env:
              TZ: ${TIMEZONE}
              # Configure application
              CF_API_EMAIL:
            envFrom:
            - secretRef:
                name: cloudflare-exporter-secret
#            resources:
#              requests:
#                cpu: 15m
#                memory: 30M
#              limits:
#                memory: 64M
    service:
      app:
        controller: *app
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 8080
    serviceMonitor:
      app:
        serviceName: *app
        enabled: true
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 5m
          scrapeTimeout: 1m
