---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nut-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/monitoring/nut-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nut-exporter-dashboard
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  path: ./kubernetes/apps/monitoring/nut-exporter/app/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
