---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.21@sha256:45c9e9287b36a3d5c7eee04690907811af51470351cd3a06878b078b5e378f13

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    enableServiceLinks: false

    env:
      TZ: "${TIMEZONE}"

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: ceph-block

    persistence:
#      config:
#        enabled: true
#        existingClaim: calibre-web-config-0
      media:
        enabled: true
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/media/books
        mountPath: /media
        readOnly: true
    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: true
          hajimari.io/icon: mdi:bookshelf
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "calibre-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
#            secretName: wildcard-tls
#      secondary:
#        enabled: true
#        ingressClassName: "internal"
#        annotations:
#          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
#          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
#        hosts:
#          - host: &hostsecond "calibre-web.${SECRET_DOMAIN}"
#            paths:
#              - path: /
#                pathType: Prefix
#        tls:
#         - hosts:
#              - *hostsecond

    resources:
      requests:
        cpu: 15m
        memory: 256Mi
      limits:
        memory: 512Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - worker
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
