---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.13.2
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    csi:
      csiAddons:
        enabled: false
      # Set when encryption/compression is enabled
      cephFSKernelMountOptions: ms_mode=secure
      # https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1875#issuecomment-1858038261
      # https://github.com/kubernetes-csi/external-provisioner/issues/1099
      attacher:
        image: registry.k8s.io/sig-storage/csi-attacher:v4.4.3
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
      resizer:
        image: registry.k8s.io/sig-storage/csi-resizer:v1.9.3
    monitoring:
      enabled: true
    logLevel: DEBUG
