---
  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
  name: "Schemas"

  on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *" # Every day at midnight
    push:
      branches: ["main"]
      paths: [".github/workflows/publish-schemas.yaml"]

  jobs:
    publish:
      name: Schemas
      runs-on: ["arc-runner-set-home-ops-amd64-runner"]
      permissions:
        contents: read
        packages: write
      steps:
        - name: Generate Token
          uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1
          id: app-token
          with:
            app-id: "${{ secrets.BOT_APP_ID }}"
            private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

        - name: Checkout
          uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
          with:
            token: "${{ steps.app-token.outputs.token }}"

        - name: Setup Homebrew
          uses: Homebrew/actions/setup-homebrew@master

        - name: Setup Workflow Tools
          shell: bash
          run: brew install kubernetes-cli

        - name: Setup Python
          uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
          with:
            python-version: 3.x

        - name: Setup Node
          uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
          with:
            node-version: 18.x

        - name: Write kubeconfig
          id: kubeconfig
          uses: timheuer/base64-to-file@adaa40c0c581f276132199d4cf60afa07ce60eac # v1
          with:
            encodedString: "${{ secrets.KUBECONFIG }}"
            fileName: kubeconfig

        - name: Download and run crd-extractor
          env:
            KUBECONFIG: "${{ steps.kubeconfig.outputs.filePath }}"
          shell: bash
          run: |
            curl -fsSL -o $GITHUB_WORKSPACE/crd-extractor.sh \
                https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/Utilities/crd-extractor.sh
            chmod +x $GITHUB_WORKSPACE/crd-extractor.sh
            bash $GITHUB_WORKSPACE/crd-extractor.sh

        - name: Deploy to Cloudflare Pages
          uses: cloudflare/wrangler-action@65240351f77618cc4d505904856f15ede9e531ef # v3
          with:
            apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
            accountId: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
            workingDirectory: /home/runner/.datree/crdSchemas
            command: pages deploy --project-name=flux-cluster-kubernetes-schemas --branch main .
